name: GitHub Actions Demo
# run-name is only supported for manual_dispatch workflows, so you can remove it for a push-triggered run
# run-name: Testing out GitHub Actions

on:
  push:

jobs:
  Basic-Workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Print a message
        run: echo "Job is executing as part of Basic workflow"
